version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'billage'
      MYSQL_ROOT_PASSWORD: 'COMPOSE_ROOT_PASSWORD'
      MYSQL_USER: 'COMPOSE_USER'
      MYSQL_PASSWORD: 'COMPOSE_PASSWORD'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-bilage:/var/lib/mysql
  redis:
    container_name: redis-billage
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=compose-redis

  spring:
    container_name: spring-boot-billage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/billage
      spring.datasource.username: COMPOSE_USER
      spring.datasource.password: COMPOSE_PASSWORD
    volumes:
      - spring-bilage:/spring/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  mysql-bilage:
    driver: local
  spring-bilage: